---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    name: "hubot-slack"
  name: "hubot-slack"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "hubot-slack"
  template:
    metadata:
      labels:
        name: "hubot-slack"
      name: "hubot-slack"
    spec:
      containers:
      - env:
        - name: "HUBOT_GRAFANA_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: "hubot-grafana-api-key"
              name: "hubot-slack"
        - name: "HUBOT_SLACK_TOKEN"
          valueFrom:
            configMapKeyRef:
              key: "hubot-slack-token"
              name: "hubot-slack"
        - name: "HUBOT_GRAFANA_HOST"
          valueFrom:
            configMapKeyRef:
              key: "hubot-grafana-host"
              name: "hubot-slack"
        - name: "HUBOT_JENKINS_URL"
          valueFrom:
            configMapKeyRef:
              key: "hubot-jenkins-url"
              name: "hubot-slack"
        image: "fabric8/hubot-slack:${project.version}"
        name: "hubot-slack"
        ports:
        - containerPort: 8080
          protocol: "TCP"
