---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/git-commit: 1d46e13d971d214d55a7dfeff632a7874b3bb11e
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/hubot-slack
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
    fabric8.io/git-branch: master
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
    fabric8.io/scm-tag: fabric8-devops-2.0.1
  labels:
    provider: fabric8
    expose: "true"
    project: hubot-slack
    version: 2.2-SNAPSHOT
    group: io.fabric8.devops.apps
  name: hubot
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: hubot-slack
    project: hubot-slack
    provider: fabric8
    group: io.fabric8.devops.apps
