---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    project: hubot-slack
    version: 2.2-SNAPSHOT
    group: io.fabric8.devops.apps
  name: hubot-slack
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 1d46e13d971d214d55a7dfeff632a7874b3bb11e
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/hubot-slack
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
      fabric8.io/git-branch: master
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
      fabric8.io/scm-tag: fabric8-devops-2.0.1
    labels:
      provider: fabric8
      expose: "true"
      project: hubot-slack
      version: 2.2-SNAPSHOT
      group: io.fabric8.devops.apps
    name: hubot
  spec:
    ports:
    - port: 80
      targetPort: 8080
    selector:
      name: hubot-slack
      project: hubot-slack
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.io/json-schema: |-
        {
          "type" : "object",
          "properties" : {
            "HUBOT_SLACK_GRAFANA_HOST" : {
              "type" : "string",
              "description" : "Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'",
              "default" : "http://grafana.default.svc.cluster.local"
            },
            "HUBOT_SLACK_GRAFANA_API_KEY" : {
              "type" : "string",
              "description" : "API key for a particular user"
            },
            "HUBOT_JENKINS_URL" : {
              "type" : "string",
              "description" : "The URL for the Jenkins CI server",
              "default" : "http://jenkins.default.svc.cluster.local"
            },
            "HUBOT_SLACK_TOKEN" : {
              "type" : "string",
              "description" : "The token for Hubot to login to Slack"
            }
          }
        }
    labels:
      name: hubot-slack
      provider: fabric8
      project: hubot-slack
      version: 2.2-SNAPSHOT
      group: io.fabric8.devops.apps
    name: hubot-slack
  data:
    hubot-jenkins-url: http://jenkins/
    hubot-grafana-host: http://grafana/
    hubot-slack-token: ${HUBOT_SLACK_TOKEN}
    hubot-grafana-api-key: ${HUBOT_SLACK_GRAFANA_API_KEY}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 1d46e13d971d214d55a7dfeff632a7874b3bb11e
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2-SNAPSHOT
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/hubot-slack
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
      fabric8.io/git-branch: master
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
      fabric8.io/scm-tag: fabric8-devops-2.0.1
    labels:
      name: hubot-slack
      provider: fabric8
      project: hubot-slack
      version: 2.2-SNAPSHOT
      group: io.fabric8.devops.apps
    name: hubot-slack
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: hubot-slack
        project: hubot-slack
        provider: fabric8
        version: 2.2-SNAPSHOT
        group: io.fabric8.devops.apps
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 1d46e13d971d214d55a7dfeff632a7874b3bb11e
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2-SNAPSHOT
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
          fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/hubot-slack
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
          fabric8.io/git-branch: master
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
          fabric8.io/scm-tag: fabric8-devops-2.0.1
        labels:
          name: hubot-slack
          provider: fabric8
          project: hubot-slack
          version: 2.2-SNAPSHOT
          group: io.fabric8.devops.apps
        name: hubot-slack
      spec:
        containers:
        - env:
          - name: HUBOT_GRAFANA_API_KEY
            valueFrom:
              configMapKeyRef:
                key: hubot-grafana-api-key
                name: hubot-slack
          - name: HUBOT_SLACK_TOKEN
            valueFrom:
              configMapKeyRef:
                key: hubot-slack-token
                name: hubot-slack
          - name: HUBOT_GRAFANA_HOST
            valueFrom:
              configMapKeyRef:
                key: hubot-grafana-host
                name: hubot-slack
          - name: HUBOT_JENKINS_URL
            valueFrom:
              configMapKeyRef:
                key: hubot-jenkins-url
                name: hubot-slack
          image: fabric8/hubot-slack:2.2-SNAPSHOT
          name: hubot-slack
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
parameters:
- description: The token for Hubot to login to Slack
  name: HUBOT_SLACK_TOKEN
- description: Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'
  name: HUBOT_SLACK_GRAFANA_HOST
  value: http://grafana2.default.svc.cluster.local
- description: API key for a particular user
  name: HUBOT_SLACK_GRAFANA_API_KEY
