---
apiVersion: "v1"
data:
  hubot-jenkins-url: "http://jenkins.default.svc.cluster.local"
  hubot-slack-token: ""
  hubot-slack-grafana-host: "http://grafana.default.svc.cluster.local"
  hubot-slack-grafana-api-key: ""
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"HUBOT_SLACK_GRAFANA_HOST\" : {\n      \"type\" : \"string\",\n      \"\
      description\" : \"Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'\"\
      ,\n      \"default\" : \"http://grafana.default.svc.cluster.local\"\n    },\n\
      \    \"HUBOT_SLACK_GRAFANA_API_KEY\" : {\n      \"type\" : \"string\",\n   \
      \   \"description\" : \"API key for a particular user\"\n    },\n    \"HUBOT_JENKINS_URL\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The URL for the\
      \ Jenkins CI server\",\n      \"default\" : \"http://jenkins.default.svc.cluster.local\"\
      \n    },\n    \"HUBOT_SLACK_TOKEN\" : {\n      \"type\" : \"string\",\n    \
      \  \"description\" : \"The token for Hubot to login to Slack\"\n    }\n  }\n\
      }"
  labels:
    name: "hubot-slack"
  name: "hubot-slack"
data:
  hubot-jenkins-url: "http://jenkins/"
  hubot-grafana-host: "http://grafana/"
  hubot-slack-token: "${HUBOT_SLACK_TOKEN}"
  hubot-grafana-api-key: "${HUBOT_SLACK_GRAFANA_API_KEY}"